name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt', 'dbt_external_tables']

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  +on_schema_change: "fail"
  jaffle_shop:
      materialized: table
      staging:
        materialized: table

seeds:
  +quote_columns: true
  jaffle_shop:
    +quote_columns: true
    raw_orders:
      +column_types:
        order_date: TEXT
