
name: 'jaffle_shop'
version: '0.21.9'
profile: 'jaffle_shop'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt', 'dbt_external_tables']

models:
  +on_schema_change: "fail"
  jaffle_shop:
      materialized: table
      staging:
        materialized: table

seeds:
  +quote_columns: true
  jaffle_shop:
    +pre-hook: "set firebolt_dont_wait_for_upload_to_s3=1"
    +quote_columns: true
    raw_orders:
      +column_types:
        order_date: TEXT
