
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt', 'dbt_external_tables']

models:
  jaffle_shop:
      orders:
        +materialized: table
        +table_type: dimension
        +indexes: |
          {
            'type': 'aggregating',
            'key_column': 'order_id',
            'aggregation': ['COUNT(DISTINCT status)', 'AVG(customer_id)']
          },
          {
            'type': 'aggregating',
            'key_column': 'customer_id',
            'aggregation': 'COUNT(DISTINCT status)'
          },
          {
            'type': 'join',
            'join_column': 'order_id',
            'dimension_column': ['customer_id', 'status']
          }
seeds:
  +quote_columns: true
  jaffle_shop:
    +quote_columns: true
    raw_orders:
      +column_types:
        order_date: TEXT
